### ISSUE TITLE
Dolly can't move "slightly larger chest"

### ISSUE THREAD

**Issue by gallowglass** [reteo/Survival-Industry#106]
The dolly can't pick up the "slightly larger chest".

**Comment by reteo** [comment]
"Slightly Larger Chest?"

**Comment by gallowglass** [comment]
From extra utilities I believe (I just closed my computer).

**Comment by reteo** [comment]
What happens when you try?  Is this the dolly from JABBA?

**Comment by gallowglass** [comment]
On Nov 15, 2016 9:14 PM, "reteo" <notifications@github.com> wrote:
>
> What happens when you try?

The chest opens.

> Is this the dolly from JABBA?

Yep.

**Comment by reteo** [comment]
On the "Instances" tab, I want you to right-click the image of the instance you are getting this problem on.  Then, click "share code."  Finally, I want you to paste the share code to a message.  This way, I can test this out on an identical Survival Industry setup.

**Comment by gallowglass** [comment]
HN5NIDYX

**Comment by reteo** [comment]
Actually, it looks like it won't work on a number of mods' storage.  After some significant testing, I have found the following list of mods' chests that will and won't work:

Will work:

* JABBA barrels (naturally)
* Refined Relocation chests
* Better Storage Chests and Lockers
* Storage Drawers
* Vanilla chests.

Won't work:

* EnderIO
* Chisel
* Ender Utilities
* MineChem (Leaded Chest)
* Better Storage's cardboard box
* BiblioCraft's framed chest.
* The vanilla ender chest
* Ender Storage's ender chest.
* Applied Energistics' sky stone chests
* Carpenter's safe.

Considering all this, I am going to have to say that there's nothing that can be done at this point.  There are too many mods that the dolly won't support, and JABBA hasn't been updated since May (even the bitbucket hasn't been updated since July), so odds are unlikely that any changes will happen anytime soon.

**Comment by gallowglass** [comment]
I figured out was something like that.  Thanks for taking the time to check
into it.

**Comment by reteo** [comment]
No problem.
