### ISSUE TITLE
Error Download

### ISSUE THREAD

**Issue by Sebolt** [reteo/Survival-Industry#121]
HELP!!! 

Error downloading jmod-1.7.10-beta1.2.3-complete.jar from http://addons.cursecdn.com/files/2395/733/jmod-1.7.10-beta1.2.3-complete.jar. Expected hash of 8a0bc0b3e19428f86e08b009a99b63d3 but got d0023ae448bcee2e146e46967c56f883 instead. Copied to FailedDownloads Folder. Cancelling install!

**Comment by reteo** [comment]
Okay, it should be fixed now.  Give it about 20 minutes (for the downloader to update) and try again.

**Comment by Sebolt** [comment]
Error downloading journeymap-1.7.10-5.1.4p1-unlimited.jar from http://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download. Expected hash of 9091571243da9b1532ba2d8fef3f2eea but got d41d8cd98f00b204e9800998ecf8427e instead. Copied to FailedDownloads Folder. Cancelling install!

**Comment by reteo** [comment]
Hmmm... I just downloaded and checked the MD5 hashes of both files. In both cases, I received the expected hash instead of the hashes you received.  I suspect there might be a problem with your copy of ATLauncher, your copy of Java, or a possible infection on the system.  Try reinstalling ATLauncher and Java (making sure it's using the latest version), and if that doesn't fix the problem, I would use something like [Malwarebytes](https://www.malwarebytes.com/) to scan the system for anything that adds changes to files.
