### ISSUE TITLE
coffee

### ISSUE THREAD

**Issue by gerb82** [reteo/Survival-Industry#25]
from the forums:
"coffee from Harvestcraft has no value whatsoever in this pack"
coffee gives no hunger at all.

**Comment by reteo** [comment]
Hunger overhaul has the ability to tweak food hunger using a JSON file.  I'll look into it when I get the chance.

**Comment by reteo** [comment]
I was unable to make the tweak.  Submitted a bug report to Hunger Overhaul (progwml6/HungerOverhaul#105)

**Comment by Rewyn** [comment]
A bit late to the party, I know.
In the MF3 pack, coffee restores fatigue, instead of hunger. (Too much was actually harmfull and could even lead to death if I remember right) 
Maybe something like that could be implemented for this pack as well? Would offer another way to reduce fatigue, as the current model is somewhat annoying in SMP.

**Comment by reteo** [comment]
MF3 uses "Better Sleeping," a different sleep mod.

I chose Somnia to ensure the player isn't protected from the dangers of nighttime mobs by sleeping, as well as allowing a "shortcut" to waiting for long processes, such as processing large amounts of ore.  At the moment, I don't really know a way to alter the fatigue meter at this time.  I can check into it, however.
