### ISSUE TITLE
Random Things

### ISSUE THREAD

**Issue by reteo** [reteo/Survival-Industry#55]
Random Things is currently not updating for Minecraft 1.7.10.  So far, there has been no problems, but it wouldn't hurt to keep an eye out for a replacement.  To help with this particular project, I'm inviting anyone who uses specific features for Random Things to comment as to the features they don't want to do without.

**Comment by reteo** [comment]
The features I'd want to keep available:

* Random events that spawn larger numbers of mobs closer to the player. (Blood Moon)
* A personal dimension. (Spectre Key)
* Materials that are solid for players, but not for mobs. (Spectre Glass)
* Rapid leaf decay.

**Comment by Rewyn** [comment]
For the first part, I already suggested the "Invasion" mod quite a while ago, but it was found unneccessary due to already having the Blood Moon from random things. Maybe it's worth a look?
There's a mod called "FastLeafDecay", so that would cover the last part.
Not really sure about the other 2 points. As for the third, I'm not sure if you'd really miss it. Yes, it's incredibly usefull, but to the point where I'd even consider it "too" usefull.

**Comment by reteo** [comment]
You sure it was invasion?  I already have the invasion mod installed.

**Comment by Rewyn** [comment]
Derp. Apocalypse was what I meant.

**Comment by reteo** [comment]
Woopsie.

**Comment by jeffpengMC** [comment]
The question is: are there any pending issuse with Random Things except known performance derps?

**Comment by reteo** [comment]
Not at the moment.  This item is simply here as a place for reports of RT replacement mods that come up.
