### ISSUE TITLE
Mob Difficulty Progression

### ISSUE THREAD

**Issue by reteo** [reteo/Survival-Industry#63]
Mobs should become harder with player progression.  This will keep the game challenging, even once the player reaches the point where they could otherwise smite mobs with reckless abandon.

**Comment by jeffpengMC** [comment]
To sum up how I view the issue as of now:

It is hard to implement in the first place, and almost impossible in SMP. The effort would be huge compared to relatively little gain. As there are several other features "in the pipe" that we acutally know how to implement, I see it unlikely that this feature will see the light of day.

**Comment by reteo** [comment]
Ah well.  We'll keep this open, just in case something eventually comes through.

**Comment by Dulciphi** [comment]
The [calendarAPI](https://github.com/ProjectZulu/JustAnotherSpawner/issues/153) may or may not be of interest when it's implemented into JAS, HarderWildlife, etc. It's most definitely of interest to me as I use extra mob mods. Spawning those mobs by season in given biomes is something I'd love to do. 

Also, I asked @Crudedragos about the possibility of adding [Scoreboard#Objectives](http://minecraft.gamepedia.com/Scoreboard#Objectives) to the list of spawn tags (conditions which limit spawning of mobs). Scoreboard objectives would be ideal, as only the player who meets the criteria for spawning mobs would trigger spawning (and despawning). Currently mobs's spawning is already restricted by a number of environmental factors. This would be an additional layer of restriction on top of that.

Otherwise, I will continue looking into MobProperties, which is another mod with powerful features in this area. It may even already have this capability and I've just not realised it yet.

**Comment by reteo** [comment]
The feature would cause too many problems in tracking multiple players in smp games and can be a potential source of griefing.  Because of this, this feature will not be added to the modpack.
