### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by ProfessorChaos31** [reteo/Survival-Industry#97]
So, whenever I attempt to create a world or enter a world that I already have created, it crashes. Not immediately, but after 5 or so minutes of loading. I am using the most current update of Survival Industry. I appreciate any help that people can give me. It also sometimes freezes in the middle of loading a world. Thank you for any help.

**Comment by reteo** [comment]
First, I'm probably going to need to see a log to determine what the problem is.  Usually, at the bottom of the ATLauncher log, there is a button labeled "Upload Log"  Click that, and once the log is uploaded, the log will show a URL for the log upload.  Simply paste that URL to this report, and hopefully, that will help me pinpoint the problem.

**Comment by ProfessorChaos31** [comment]
The launcher would freeze when I clicked on "Upload Log." So I did what I could and got the crash report from OpenEye. Will that work?
http://openeye.openmods.info/crashes/56b0042e468d5a514787f0ae5a69a372

**Comment by ProfessorChaos31** [comment]
I had to copy the log instead. Hopefully both of these will work?
http://paste.atlauncher.com/view/e4ba46e5

**Comment by reteo** [comment]
Have you tried generating a new world?  Does the error happen in that case?

**Comment by ProfessorChaos31** [comment]
Alright, thank you.
