### ISSUE TITLE
how to add harder ores to the 6 level mining config?

### ISSUE THREAD

**Issue by hyperkiller3** [reteo/Survival-Industry#98]
I really liked harder ores, so I threw it in, but in doing so, I made all the common ores revert to the entry mining level (so iron and gold is entry level and no longer high level required)

How would I add harder ores into the config?

**Comment by reteo** [comment]
Survival Industry actually alters the mining level of all the ores in all the included mods in the pack.  Unfortunately, Harder Ores completely removes them and uses its own instead.  Additionally, the mod would conflict with the existing modpack configurations for Custom Ore Generation.  

Because of this, the mod is pretty much incompatible with Survival Industry at this time.

I can put some work into adding it in a future update, but will need to see how to make things work.

**Comment by hyperkiller3** [comment]
Yeah, after like a few days I realized I couldn't use the grinder or anything like that processes with the harder ores.

**Comment by reteo** [comment]
That's actually incompatibility with RotaryCraft.  There's also the sluice, which removes the challenge of the advanced mining progression (you can quickly advance to bronze-level mining simply by using the sluice to collect enough tin and copper to make a bronze pickaxe).  Of course, there's also the fact that both mod and modpack each has its own Custom Ore Generation configuration, and SI heavily modifies ores specific to the modpack; third party ores aren't altered.

All in all, I recommend against using Harder Ores for this modpack, because that mod 1) conflicts with the modpack's design, and 2) doesn't interact well with RotaryCraft, which is kind of what the pack is centered around.

**Comment by SvenKayser** [comment]
Just to get an angle on the motivation behind adding Harder Ores: What does it add that SI doesn't?

**Comment by reteo** [comment]
See [here]( http://reasonable-realism.wikia.com/wiki/Harder_Ores).

**Comment by reteo** [comment]
This is a bit of clarification:

Simply put, you can mine the same block of ore several times, each time, the number of dots on the ore's surface reduces by one.  Once there's ony one dot left, the ore is completely mined.  Instead of ore blocks, mining ores will drop ore chunks (each equal to one nugget), which can be processed in Reasonable Realism machines to provide more ore per block.

The main two reasons I do not add Harder Ores to the pack are as follows:

1. The use of the sluice can circumvent the mining progression, resulting in a player getting high-level ores well before they're ready to mine them.  Since they only need three ingots of ore (or crystal) to make the pickaxe of that material, this can become an exploit.
2. The ore chunks that drop from Harder Ores are not supported in RotaryCraft machines; and it's inadvisable to make recipes for them, since the chunks provide one nugget of ore, while the RotaryCraft machines output ingot-sized amounts of material; this would produce a massive ore multiplier without even needing the extractor.

I'm sorry, but after doing some homework, I'm going to have to say support for Harder Ores will simply undermine the game's design.

**Comment by Rewyn** [comment]
I think there's 2 rather simple ways to deal with those 2 points actually. 
1. The sluice is easily configured to what it can find, or disabled in general.
2. There's a recipe with some reasonable realism machine, which allows raw ore to be packed into something, that can then be used in RoC machines. 
The way it's done in the Revolution pack, is that you need an IE Blast Furnace/Arc Furnace or Alloy Smelter to refine the raw ore into their regular ore blocks, which you can then process in RoC machines like usual.
Harder Ores is really nice in the way it's designed, I'd say.
Have to admit, I didn't exactly keep myself up to date lately with SI, so not sure how it'll go with the rest of the progression. I'd think it could be a very nice addition, however, if done right.

**Comment by reteo** [comment]
Well, we can always revert back to my original objection; HO replaces COG configurations with its own, and I really don't want to go through them by hand, changing hardness, blast resistance, and mining level for each "iteration" of an ore block.

**Comment by Rewyn** [comment]
I didn't exactly mean to try to convice you to add it to the pack, more of a way if saying "if you want to add it, those 2 points are somewhat easily fixed".
I'd assume using your own COG configuration, instead of HO's shouldn't be too much of a problem either, however not wanting to change each's blocks hardness, blast resistance and mining level by hand, that I can understand quite well.
After all, it's your call if you'd want to include it in the pack. I just said I liked it, and think it could be a nice addition. Then again, that holds true for most packs.
